name: micro-url-shortener-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: 
          make test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - name: Extract Version
        id: version_step
        run: |
          MY_DOCKERHUB_REPOSITORY="mavridis/url-shortener"
          echo "##[set-output name=latest_tag;]$MY_DOCKERHUB_REPOSITORY:latest"  
          echo "##[set-output name=version_tag;]$MY_DOCKERHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ steps.version_step.outputs.version_tag }}
            ${{ steps.version_step.outputs.latest_tag }}